import { Question } from "../types";

export const frontendQuestions: Question[] = [
  {
    id: "fe_1",
    text: "In React 18 & 19, what is the primary architectural purpose of 'Concurrent Features' (like startTransition and useTransition)?",
    options: [
      "To run React components on separate threads in the browser using Web Workers.",
      "To allow React to pause, interrupt, and resume rendering updates in the background, keeping the main thread responsive for user inputs like typing.",
      "To perform automatic database connection pooling in serverless environments.",
      "To translate JS components into native WebAssembly binaries at compile-time."
    ],
    correctAnswerIndex: 1,
    explanation: "Concurrent rendering lets React prioritize urgent updates (like typing in an input) over non-urgent updates (like filtering a long list). Non-urgent renders are marked with `startTransition` and can be interrupted if the user types again."
  },
  {
    id: "fe_2",
    text: "You run a performance audit and find a high 'Interaction to Next Paint' (INP) score. Which of the following is the most direct way to optimize INP?",
    options: [
      "Preloading all page images inside the HTML head.",
      "Splitting heavy JavaScript event handler tasks into smaller chunks using requestIdleCallback, setTimeout, or scheduler.yield() to yield back to the main browser thread.",
      "Converting all JPEG images to WebP.",
      "Upgrading the client's network to a faster 5G standard."
    ],
    correctAnswerIndex: 1,
    explanation: "INP measures the time it takes for a page to physically paint a frame after a user interacts with it. Heavy synchronous JavaScript in event handlers blocks the main thread, delaying the paint. Yielding to the browser resolves this."
  },
  {
    id: "fe_3",
    text: "What causes a 'Hydration Mismatch' in a Next.js (App Router) or general SSR application, and how does it impact user experience?",
    options: [
      "The server is running on a different time zone than the user's browser, leading to database write conflicts.",
      "The pre-rendered HTML structure sent from the server does not exactly match the initial DOM structure generated by React on the client. It causes visual flickering, broken layouts, and interactive components failing to function.",
      "The browser fails to load CSS files over HTTPS. It blocks the page from rendering at all.",
      "The system runs out of physical memory on the backend container, crashing the dev server."
    ],
    correctAnswerIndex: 1,
    explanation: "Hydration matches pre-rendered HTML with client JS. If they differ (e.g., using `new Date()` or `window` objects during initial render), React throws a hydration mismatch error, which can break client-side event binding and cause visual bugs."
  },
  {
    id: "fe_4",
    text: "Consider the JavaScript Event Loop. What is the execution order of the following console.logs? \n```js\nconsole.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nrequestAnimationFrame(() => console.log('4'));\n```",
    options: [
      "1, 2, 3, 4",
      "1, 3, 4, 2",
      "1, 3, 2, 4",
      "1, 4, 3, 2"
    ],
    correctAnswerIndex: 1,
    explanation: "Sync code runs first ('1'). Microtasks (Promises) run immediately after sync code ('3'). requestAnimationFrame ('4') runs before the next browser paint. Macrotasks (setTimeout '2') run in the next event loop tick after painting."
  },
  {
    id: "fe_5",
    text: "Why should you avoid using the index of an array as the `key` prop in React lists when the list can be dynamically sorted, filtered, or reordered?",
    options: [
      "It raises a severe TypeScript syntax error that blocks compilation.",
      "React will use index keys to identify DOM nodes. If the order changes, React may reuse incorrect DOM elements, causing state leaks (like text input contents staying in place) and inefficient re-renders.",
      "It disables Tailwind CSS layout classes for those list items.",
      "It forces the list to render on the backend server instead of the browser."
    ],
    correctAnswerIndex: 1,
    explanation: "React relies on the `key` to identify which items changed, were added, or were removed. If indexes are keys and items are reordered, React assumes the item at index X is the same, mismatching local component state (like inputs) with the data."
  },
  {
    id: "fe_6",
    text: "You are building a modal component. To make it strictly accessible (WAI-ARIA compliant), what keyboard and focus behaviors must you implement?",
    options: [
      "Disable the mouse entirely while the modal is open.",
      "Ensure pressing Escape closes the modal, and implement a 'Focus Trap' so pressing Tab cycles focus exclusively through interactive elements inside the modal, returning focus to the trigger button upon closing.",
      "Ensure all text is styled with at least a 24px font size.",
      "Add an aria-live='polite' tag to every div inside the modal."
    ],
    correctAnswerIndex: 1,
    explanation: "Accessible modals must trap focus to prevent screen readers and keyboard users from interacting with content behind the modal. Escape must close it, and focus must return to the original trigger to maintain sequential keyboard flow."
  },
  {
    id: "fe_7",
    text: "What is the primary benefit of CSS Container Queries (`@container`) over standard Media Queries (`@media`) in modern component-driven development?",
    options: [
      "Container queries allow styling elements based on the server's CPU temperature.",
      "Container queries allow elements to style themselves based on the width of their parent container instead of the global browser viewport, making components truly modular and self-contained.",
      "Container queries load 10x faster and run on GPU threads.",
      "Container queries automatically convert flexbox layouts into CSS grids."
    ],
    correctAnswerIndex: 1,
    explanation: "Media queries only inspect the viewport. A component placed in a narrow sidebar and a wide main panel would see the same viewport width. Container queries let the component adapt layout depending on the space its container provides."
  },
  {
    id: "fe_8",
    text: "How does the `useMemo` hook optimize rendering performance in React, and when should you actually avoid using it?",
    options: [
      "It automatically runs code in parallel. Avoid using it on mobile devices.",
      "It caches the result of an expensive calculation between renders. Avoid it for cheap operations, as the overhead of dependency comparison and memory allocation can exceed the benefit.",
      "It caches React components in the browser's IndexedDB database. Avoid it for dynamic lists.",
      "It bypasses the React reconciliation engine entirely. Avoid it in forms."
    ],
    correctAnswerIndex: 1,
    explanation: "`useMemo` prevents recalculation on every render. If the computation is trivial (e.g., adding two numbers), the memory and check cost of dependencies is waste. Use it for heavy computations (like sorting 1000 items) or preserving reference equality."
  },
  {
    id: "fe_9",
    text: "When implementing 'Virtual Lists' (windowing) for rendering 100,000 items, how does it optimize browser memory and CPU consumption?",
    options: [
      "It stores all items in a service worker memory cluster.",
      "It only renders the tiny fraction of items that are currently visible within the scroll viewport, dynamically swapping out DOM nodes as the user scrolls, avoiding rendering 100k physical elements.",
      "It compresses the list into a single compressed string before rendering.",
      "It runs the list through a WebGL canvas instead of HTML DOM."
    ],
    correctAnswerIndex: 1,
    explanation: "Rendering 100k DOM elements will freeze any browser due to memory limits and layout computations. Virtual lists render only the visible items (plus a tiny buffer), repositioning them dynamically, keeping DOM node count constant."
  },
  {
    id: "fe_10",
    text: "What does the CSS property `content-visibility: auto` do, and how does it benefit page initialization speed?",
    options: [
      "It automatically translates page content to the user's preferred language.",
      "It tells the browser to skip rendering (layout and painting) of off-screen elements until they approach the viewport, significantly reducing initial load times.",
      "It makes the page invisible to ad blockers.",
      "It forces all text fonts to load synchronously before rendering anything."
    ],
    correctAnswerIndex: 1,
    explanation: "`content-visibility: auto` allows the browser to skip the rendering and layout steps of off-screen components. For long, resource-heavy pages, this speeds up the initial paint since the browser avoids calculating off-screen geometry."
  },
  {
    id: "fe_11",
    text: "What is 'Event Delegation' in vanilla JavaScript, and what memory benefit does it offer?",
    options: [
      "It delegates event handling to the backend server. It frees up client CPU.",
      "It attaches a single event listener to a common parent element rather than individual listeners on multiple child elements, saving memory by utilizing event bubbling.",
      "It runs event handlers in parallel on separate worker threads.",
      "It automatically removes unused variables from the closure stack."
    ],
    correctAnswerIndex: 1,
    explanation: "Instead of binding 1,000 click listeners to 1,000 list items (which consumes extensive memory), event delegation attaches a single listener to the parent `<ul>`. Clicking a `<li>` bubbles the event up, and `event.target` identifies the click source."
  },
  {
    id: "fe_12",
    text: "What is the primary difference between standard microtasks (e.g., Promise.then) and macrotasks (e.g., setTimeout) in the JavaScript execution context?",
    options: [
      "Macrotasks run before microtasks in every event loop iteration.",
      "The microtask queue is fully exhausted (cleared) immediately after the current synchronous script runs and before yielding to rendering or macrotasks, whereas macrotasks run one by one.",
      "Microtasks only run in Web Worker threads.",
      "Macrotasks are not supported in Node.js server environments."
    ],
    correctAnswerIndex: 1,
    explanation: "At the end of a execution turn, the browser checks the microtask queue and runs all queued microtasks until the queue is completely empty (even if new ones are added). Only then does it yield to painting or run a macrotask."
  },
  {
    id: "fe_13",
    text: "When implementing responsive layouts in Tailwind CSS, what is the 'mobile-first' rule you must keep in mind?",
    options: [
      "You must design layouts on physical phones before editing code.",
      "Tailwind's naked prefix (e.g., w-full) applies to all screens by default, and responsive overrides (e.g., md:w-1/2) act as min-width media queries, applying from that breakpoint upward.",
      "Tailwind automatically scales down large desktop layouts using a zoom formula.",
      "You cannot use grid layouts on mobile viewports."
    ],
    correctAnswerIndex: 1,
    explanation: "Tailwind's responsive design uses min-width queries. Unprefixed classes target mobile, while prefixes like `md:` apply to viewports *greater than or equal to* 768px. Desktop-first overrides are not the default."
  },
  {
    id: "fe_14",
    text: "What is 'Layout Shift' (measured by the CLS Core Web Vital), and what is a common cause?",
    options: [
      "When the user shifts their device from portrait to landscape mode. Caused by accelerometers.",
      "Unstable visual elements shifting positions during page load. Commonly caused by images or iframes loaded without explicit width and height dimensions, or dynamic ad insertions.",
      "When a user clicks a button and is redirected to a new page.",
      "A bug where CSS styles fail to compile into standard class strings."
    ],
    correctAnswerIndex: 1,
    explanation: "Cumulative Layout Shift (CLS) measures visual instability. If an image loads without dimensions, the page renders 0px tall first, then suddenly pops open to full height when the image arrives, pushing down text. Pre-sizing prevents this."
  },
  {
    id: "fe_15",
    text: "Why does React require you to return a cleanup function inside `useEffect` when setting up a global event listener, WebSocket connection, or interval timer?",
    options: [
      "Without a cleanup, the component will fail to compile under strict mode.",
      "To prevent memory leaks and duplicate bindings; otherwise, when the component unmounts and remounts, old event listeners and connections will persist indefinitely.",
      "To tell the React engine to store the event listener in local storage.",
      "To trigger a hard refresh of the browser window."
    ],
    correctAnswerIndex: 1,
    explanation: "If you don't clean up subscriptions, interval timers, or event listeners, they remain active in memory even after the component is destroyed. This wastes resources, runs background code, and can cause crashes or double-triggers."
  },
  {
    id: "fe_16",
    text: "What does the React 19 hook `useActionState` (formerly `useFormState`) simplify in application state management?",
    options: [
      "It simplifies storing form inputs inside the user's browser cookie file.",
      "It streamlines handling async operations in forms, automatically tracking pending states, return values, and errors directly from async actions.",
      "It translates HTML form inputs into automated GraphQL mutations.",
      "It manages websocket communication states for multi-user chat rooms."
    ],
    correctAnswerIndex: 1,
    explanation: "`useActionState` takes an async action and returns the current state, a dispatch function, and a boolean `isPending`. It eliminates manual boilerplate code for tracking `loading`, `error`, and `data` when submitting forms."
  },
  {
    id: "fe_17",
    text: "How do you prevent a 'Keyboard Trap' in custom interactive elements (e.g., custom dropdowns or modals)?",
    options: [
      "By disabling keyboard navigation entirely for assistive users.",
      "By ensuring that keyboard users can navigate into AND out of the component using standard keys (like Tab, Shift+Tab, or Escape), without getting stuck in an infinite focus loop.",
      "By forcing the user to use the mouse to click an invisible exit button.",
      "By binding the spacebar to automatically trigger the browser's reload command."
    ],
    correctAnswerIndex: 1,
    explanation: "A keyboard trap occurs when a user tabs into a component but cannot leave it via standard keystrokes. Custom components must listen for tab navigations and correctly pass focus back to the surrounding DOM."
  },
  {
    id: "fe_18",
    text: "What is the primary visual difference between the browser metrics 'First Contentful Paint' (FCP) and 'Largest Contentful Paint' (LCP)?",
    options: [
      "FCP measures when any part of the DOM (text, image, canvas) is first rendered on screen; LCP measures when the primary, largest above-the-fold content element is fully visible.",
      "FCP measures text rendering only; LCP measures video files.",
      "FCP is only measured on mobile; LCP is measured on desktop.",
      "There is no difference; they are different terms for the exact same event."
    ],
    correctAnswerIndex: 0,
    explanation: "FCP detects when the screen first shows *anything* other than a white page (e.g., a header or loading spinner). LCP is a user-centric metric measuring when the main content (e.g., hero image or large title) is readable."
  },
  {
    id: "fe_19",
    text: "Why does utilizing deep object destructuring inside a React component's render body sometimes lead to performance bottlenecks if not structured carefully?",
    options: [
      "Because destructuring triggers a full garbage collection loop in Chrome.",
      "If you destructure props or objects and pass them as new references (like creating new object literals on the fly) to children, it breaks React.memo shallow comparison checks.",
      "Destructuring is not supported in ES6, requiring heavy transpilation bloating.",
      "It forces React to compile all JSX elements into pure WebAssembly."
    ],
    correctAnswerIndex: 1,
    explanation: "Destructuring itself is fast, but if you restructure those values into new objects (e.g., `const config = { a, b }`) inside the render body, a new object reference is created every render, forcing child components to re-render."
  },
  {
    id: "fe_20",
    text: "What is the security risk of using `target='_blank'` on an HTML anchor tag without adding `rel='noopener noreferrer'`?",
    options: [
      "It allows the destination website to read the user's browser history.",
      "It exposes the opened page to a performance vulnerability, crashing the tab.",
      "The newly opened page gets access to the original window's `window.opener` object, allowing it to redirect the original tab to a malicious/phishing URL in the background.",
      "It lets the destination website download files onto the user's hard drive."
    ],
    correctAnswerIndex: 2,
    explanation: "Without `noopener`, the newly opened window can manipulate the source tab via `window.opener.location`. This is a classic vulnerability known as tabnabbing, where a fake login form can be shown in the user's original tab."
  }
];
